name: Daily Stock Data Scrape

on:
  schedule:
    - cron: '0 2 * * 1-5'  # 每个工作日凌晨2点UTC运行（避开股市休市日）
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # 与environment.yml保持一致

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run stock scraper (akshare version)
      run: python scrape_stock_akshare.py
      env:
        TICKERS: "AAPL,MSFT,GOOGL,TSLA,NVDA"  # 可自定义股票列表
        START: "2024-01-01"  # 可自定义开始日期

    - name: Commit and push data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add stock_data.csv
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update stock data - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        fi
